### PR TITLE
demo theme development for pico theme on branch demo2

### PR DESCRIPTION
**Pull request by ratulkhan74**
Created structure for the theme. added all necessary files and folders, created reusable component called pattern in block theme, worked on home page

### CODE REVIEW

**Comment by stratofax** [comment]
@ratulkhan74 is this PR still active or can we close it?

**Comment by ratulkhan74** [comment]
> @ratulkhan74 is this PR still active or can we close it?

yeah, we don't need this PR anymore coz we are working on new theme

**Comment by stratofax** [comment]
OK, PR closed 👍

**Comment by stratofax** [comment]
@ratulkhan74 OK to delete the `demo2` branch as well?

**Pull request closed without merging**
